[package]
name = "ore-cli"
version = "0.4.12-alpha"
description = "A command line interface for the Ore program."
license = "Apache-2.0"
edition = "2021"

[[bin]]
name = "ore"
path = "src/main.rs"

[features]
default = []
admin = []
metrics = ["tracing", "tracing-subscriber" , "tracing-opentelemetry", "tracing-core", "opentelemetry", "opentelemetry-otlp", "opentelemetry_sdk", "opentelemetry-semantic-conventions", "opentelemetry-stdout"]

[dependencies]
bincode = "1.3.3"
bs58 = "0.5.1"
cached = "0.46.1"
chrono = "0.4.34"
clap = { version = "4.4.12", features = ["derive"] }
futures = "0.3.30"
log = "0.4"
ore = { version = "1.2.1", package = "ore-program" }
rand = "0.8.4"
solana-cli-config = "1.18.5"
solana-client = "^1.16"
solana-program = "^1.16"
solana-sdk = "^1.16"
solana-transaction-status = "^1.16"
spl-token = { version = "^4", features = ["no-entrypoint"] }
spl-associated-token-account = { version = "^2.2", features = [ "no-entrypoint" ] }
tokio = "1.35.1"
tracing = { version = "0.1.40", optional = true }
tracing-core = {version = "0.1.32", optional = true }
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "fmt", "local-time"]  , optional = true }
tracing-opentelemetry = { version = "0.23.0", optional = true }
opentelemetry = {version = "0.22.0", optional = true }
opentelemetry_sdk = { version = "0.22.1", optional = true, features = ["rt-tokio"] }
opentelemetry-semantic-conventions = {version = "0.14.0", optional = true}
opentelemetry-otlp = { version = "0.15.0", optional = true, features = ["metrics"] }
opentelemetry-stdout = {version = "0.3.0", optional = true , features = ["metrics", "logs"]}